version: '3.1'

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      TZ: Asia/Taipei
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: mydb
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./datadir:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 7890:8080

networks:
  default:
    external:
      name: svc-overlay-network
